#![allow(dead_code, non_camel_case_types)]

pub type SQLHANDLE = *mut std::ffi::c_void;
pub type SQLHENV = SQLHANDLE;
pub type SQLHDBC = SQLHANDLE;
pub type SQLHSTMT = SQLHANDLE;
pub type SQLHWND = SQLHANDLE;
pub type SQLRETURN = i16;
pub type SQLSMALLINT = i16;
pub type SQLINTEGER = i32;
pub type SQLUSMALLINT = u16;
pub type SQLUINTEGER = u32;
pub type SQLLEN = isize;
pub type SQLULEN = usize;
pub type SQLPOINTER = *mut std::ffi::c_void;
pub type SQLCHAR = u8;
pub type SQLWCHAR = u16;

// Return codes
pub const SQL_SUCCESS: SQLRETURN = 0;
pub const SQL_SUCCESS_WITH_INFO: SQLRETURN = 1;
pub const SQL_NO_DATA: SQLRETURN = 100;
pub const SQL_ERROR: SQLRETURN = -1;
pub const SQL_INVALID_HANDLE: SQLRETURN = -2;
pub const SQL_NEED_DATA: SQLRETURN = 99;

// Handle types
pub const SQL_HANDLE_ENV: SQLSMALLINT = 1;
pub const SQL_HANDLE_DBC: SQLSMALLINT = 2;
pub const SQL_HANDLE_STMT: SQLSMALLINT = 3;

// Env attributes
pub const SQL_ATTR_ODBC_VERSION: SQLINTEGER = 200;
pub const SQL_OV_ODBC3: SQLINTEGER = 3;
pub const SQL_OV_ODBC2: SQLINTEGER = 2;

// Connection attributes
pub const SQL_ATTR_AUTOCOMMIT: SQLINTEGER = 102;
pub const SQL_ATTR_CONNECTION_TIMEOUT: SQLINTEGER = 113;
pub const SQL_ATTR_LOGIN_TIMEOUT: SQLINTEGER = 103;
pub const SQL_AUTOCOMMIT_ON: SQLUINTEGER = 1;
pub const SQL_AUTOCOMMIT_OFF: SQLUINTEGER = 0;

// Data types
pub const SQL_CHAR: SQLSMALLINT = 1;
pub const SQL_VARCHAR: SQLSMALLINT = 12;
pub const SQL_LONGVARCHAR: SQLSMALLINT = -1;
pub const SQL_INTEGER: SQLSMALLINT = 4;
pub const SQL_SMALLINT: SQLSMALLINT = 5;
pub const SQL_FLOAT: SQLSMALLINT = 6;
pub const SQL_REAL: SQLSMALLINT = 7;
pub const SQL_DOUBLE: SQLSMALLINT = 8;
pub const SQL_DATETIME: SQLSMALLINT = 9;
pub const SQL_TYPE_DATE: SQLSMALLINT = 91;
pub const SQL_TYPE_TIME: SQLSMALLINT = 92;
pub const SQL_TYPE_TIMESTAMP: SQLSMALLINT = 93;
pub const SQL_BIGINT: SQLSMALLINT = -5;
pub const SQL_TINYINT: SQLSMALLINT = -6;
pub const SQL_BIT: SQLSMALLINT = -7;
pub const SQL_WCHAR: SQLSMALLINT = -8;
pub const SQL_WVARCHAR: SQLSMALLINT = -9;
pub const SQL_WLONGVARCHAR: SQLSMALLINT = -10;
pub const SQL_NUMERIC: SQLSMALLINT = 2;
pub const SQL_DECIMAL: SQLSMALLINT = 3;
pub const SQL_BINARY: SQLSMALLINT = -2;
pub const SQL_VARBINARY: SQLSMALLINT = -3;
pub const SQL_LONGVARBINARY: SQLSMALLINT = -4;
pub const SQL_GUID: SQLSMALLINT = -11;

// C data types
pub const SQL_C_CHAR: SQLSMALLINT = 1;
pub const SQL_C_WCHAR: SQLSMALLINT = -8;
pub const SQL_C_LONG: SQLSMALLINT = 4;
pub const SQL_C_SLONG: SQLSMALLINT = -16;
pub const SQL_C_SHORT: SQLSMALLINT = 5;
pub const SQL_C_FLOAT: SQLSMALLINT = 7;
pub const SQL_C_DOUBLE: SQLSMALLINT = 8;
pub const SQL_C_DEFAULT: SQLSMALLINT = 99;
pub const SQL_C_SBIGINT: SQLSMALLINT = -25;

// NULL indicator
pub const SQL_NULL_DATA: SQLLEN = -1;
pub const SQL_NTS: SQLLEN = -3;
pub const SQL_NO_TOTAL: SQLLEN = -4;

// SQLDriverConnect flags
pub const SQL_DRIVER_NOPROMPT: SQLUSMALLINT = 0;
pub const SQL_DRIVER_COMPLETE: SQLUSMALLINT = 1;
pub const SQL_DRIVER_PROMPT: SQLUSMALLINT = 2;
pub const SQL_DRIVER_COMPLETE_REQUIRED: SQLUSMALLINT = 3;

// SQLGetInfo types
pub const SQL_MAX_DRIVER_CONNECTIONS: SQLUSMALLINT = 0;
pub const SQL_DRIVER_NAME: SQLUSMALLINT = 6;
pub const SQL_DRIVER_VER: SQLUSMALLINT = 7;
pub const SQL_DBMS_NAME: SQLUSMALLINT = 17;
pub const SQL_DBMS_VER: SQLUSMALLINT = 18;
pub const SQL_SEARCH_PATTERN_ESCAPE: SQLUSMALLINT = 14;
pub const SQL_SERVER_NAME: SQLUSMALLINT = 13;
pub const SQL_DATABASE_NAME: SQLUSMALLINT = 16;
pub const SQL_USER_NAME: SQLUSMALLINT = 47;
pub const SQL_DATA_SOURCE_NAME: SQLUSMALLINT = 2;
pub const SQL_IDENTIFIER_QUOTE_CHAR: SQLUSMALLINT = 29;
pub const SQL_CATALOG_NAME_SEPARATOR: SQLUSMALLINT = 41;
pub const SQL_CATALOG_TERM: SQLUSMALLINT = 42;
pub const SQL_SCHEMA_TERM: SQLUSMALLINT = 39;
pub const SQL_TABLE_TERM: SQLUSMALLINT = 45;
pub const SQL_NEED_LONG_DATA_LEN: SQLUSMALLINT = 111;
pub const SQL_GETDATA_EXTENSIONS: SQLUSMALLINT = 81;
pub const SQL_GD_ANY_COLUMN: SQLUINTEGER = 1;
pub const SQL_GD_ANY_ORDER: SQLUINTEGER = 2;
pub const SQL_CURSOR_COMMIT_BEHAVIOR: SQLUSMALLINT = 23;
pub const SQL_CURSOR_ROLLBACK_BEHAVIOR: SQLUSMALLINT = 24;
pub const SQL_TXN_CAPABLE: SQLUSMALLINT = 46;
pub const SQL_TXN_ISOLATION_OPTION: SQLUSMALLINT = 72;
pub const SQL_DEFAULT_TXN_ISOLATION: SQLUSMALLINT = 26;
pub const SQL_CONCAT_NULL_BEHAVIOR: SQLUSMALLINT = 22;
pub const SQL_COLUMN_ALIAS: SQLUSMALLINT = 87;
pub const SQL_CORRELATION_NAME: SQLUSMALLINT = 74;
pub const SQL_EXPRESSIONS_IN_ORDERBY: SQLUSMALLINT = 27;
pub const SQL_GROUP_BY: SQLUSMALLINT = 88;
pub const SQL_MAX_COLUMNS_IN_GROUP_BY: SQLUSMALLINT = 97;
pub const SQL_MAX_COLUMNS_IN_ORDER_BY: SQLUSMALLINT = 99;
pub const SQL_MAX_COLUMNS_IN_SELECT: SQLUSMALLINT = 100;
pub const SQL_ORDER_BY_COLUMNS_IN_SELECT: SQLUSMALLINT = 90;
pub const SQL_OUTER_JOINS: SQLUSMALLINT = 38;
pub const SQL_QUOTED_IDENTIFIER_CASE: SQLUSMALLINT = 93;
pub const SQL_SPECIAL_CHARACTERS: SQLUSMALLINT = 94;
pub const SQL_MAX_IDENTIFIER_LEN: SQLUSMALLINT = 10005;
pub const SQL_MAX_CATALOG_NAME_LEN: SQLUSMALLINT = 34;
pub const SQL_MAX_SCHEMA_NAME_LEN: SQLUSMALLINT = 32;
pub const SQL_MAX_TABLE_NAME_LEN: SQLUSMALLINT = 35;
pub const SQL_MAX_COLUMN_NAME_LEN: SQLUSMALLINT = 30;
pub const SQL_ACCESSIBLE_TABLES: SQLUSMALLINT = 19;
pub const SQL_ACCESSIBLE_PROCEDURES: SQLUSMALLINT = 20;
pub const SQL_MULT_RESULT_SETS: SQLUSMALLINT = 36;
pub const SQL_MULTIPLE_ACTIVE_TXN: SQLUSMALLINT = 37;
pub const SQL_DESCRIBE_PARAMETER: SQLUSMALLINT = 10002;
pub const SQL_NON_NULLABLE_COLUMNS: SQLUSMALLINT = 75;
pub const SQL_NULL_COLLATION: SQLUSMALLINT = 85;
pub const SQL_PROCEDURES: SQLUSMALLINT = 21;
pub const SQL_SUBQUERIES: SQLUSMALLINT = 95;
pub const SQL_UNION: SQLUSMALLINT = 96;

// Nullable
pub const SQL_NO_NULLS: SQLSMALLINT = 0;
pub const SQL_NULLABLE: SQLSMALLINT = 1;
pub const SQL_NULLABLE_UNKNOWN: SQLSMALLINT = 2;

// SQLFreeStmt options
pub const SQL_CLOSE: SQLUSMALLINT = 0;
pub const SQL_DROP: SQLUSMALLINT = 1;
pub const SQL_UNBIND: SQLUSMALLINT = 2;
pub const SQL_RESET_PARAMS: SQLUSMALLINT = 3;

// SQLColAttribute field identifiers
pub const SQL_DESC_COUNT: SQLUSMALLINT = 1001;
pub const SQL_DESC_TYPE: SQLUSMALLINT = 1002;
pub const SQL_DESC_LENGTH: SQLUSMALLINT = 1003;
pub const SQL_DESC_OCTET_LENGTH: SQLUSMALLINT = 1013;
pub const SQL_DESC_PRECISION: SQLUSMALLINT = 1005;
pub const SQL_DESC_SCALE: SQLUSMALLINT = 1006;
pub const SQL_DESC_NULLABLE: SQLUSMALLINT = 1008;
pub const SQL_DESC_NAME: SQLUSMALLINT = 1011;
pub const SQL_DESC_UNNAMED: SQLUSMALLINT = 1012;
pub const SQL_DESC_CONCISE_TYPE: SQLUSMALLINT = 2;
pub const SQL_DESC_DISPLAY_SIZE: SQLUSMALLINT = 6;
pub const SQL_DESC_LABEL: SQLUSMALLINT = 18;
pub const SQL_DESC_TABLE_NAME: SQLUSMALLINT = 15;
pub const SQL_DESC_TYPE_NAME: SQLUSMALLINT = 14;
pub const SQL_DESC_AUTO_UNIQUE_VALUE: SQLUSMALLINT = 11;
pub const SQL_DESC_CASE_SENSITIVE: SQLUSMALLINT = 12;
pub const SQL_DESC_FIXED_PREC_SCALE: SQLUSMALLINT = 9;
pub const SQL_DESC_SEARCHABLE: SQLUSMALLINT = 13;
pub const SQL_DESC_UNSIGNED: SQLUSMALLINT = 8;
pub const SQL_DESC_UPDATABLE: SQLUSMALLINT = 10;

// Statement attributes
pub const SQL_ATTR_ROW_ARRAY_SIZE: SQLINTEGER = 27;
pub const SQL_ATTR_ROWS_FETCHED_PTR: SQLINTEGER = 26;
pub const SQL_ATTR_ROW_STATUS_PTR: SQLINTEGER = 25;
pub const SQL_ATTR_CURSOR_TYPE: SQLINTEGER = 6;
pub const SQL_ATTR_CONCURRENCY: SQLINTEGER = 7;
pub const SQL_ATTR_QUERY_TIMEOUT: SQLINTEGER = 0;
pub const SQL_ATTR_MAX_ROWS: SQLINTEGER = 1;
pub const SQL_ATTR_NOSCAN: SQLINTEGER = 2;
pub const SQL_ATTR_MAX_LENGTH: SQLINTEGER = 3;
pub const SQL_ATTR_CURSOR_SCROLLABLE: SQLINTEGER = -1;
pub const SQL_ATTR_CURSOR_SENSITIVITY: SQLINTEGER = -2;

// Fetch orientation
pub const SQL_FETCH_NEXT: SQLSMALLINT = 1;
pub const SQL_ROW_SUCCESS: SQLUSMALLINT = 0;
pub const SQL_ROW_ERROR: SQLUSMALLINT = 5;
pub const SQL_ROW_NOROW: SQLUSMALLINT = 3;
pub const SQL_FETCH_FIRST: SQLSMALLINT = 2;

// Info return values
pub const SQL_TC_ALL: SQLUSMALLINT = 2;

// SQL_COLUMN_DISPLAY_SIZE etc for isql compat
pub const SQL_COLUMN_DISPLAY_SIZE: SQLUSMALLINT = 6;
pub const SQL_COLUMN_TYPE: SQLUSMALLINT = 2;
pub const SQL_COLUMN_LENGTH: SQLUSMALLINT = 3;
pub const SQL_COLUMN_NAME: SQLUSMALLINT = 1;
pub const SQL_COLUMN_NULLABLE: SQLUSMALLINT = 7;
pub const SQL_COLUMN_LABEL: SQLUSMALLINT = 18;

// Transaction completion types
pub const SQL_COMMIT: SQLSMALLINT = 0;
pub const SQL_ROLLBACK: SQLSMALLINT = 1;

// Additional C types
pub const SQL_C_BIT: SQLSMALLINT = -7;
pub const SQL_C_BINARY: SQLSMALLINT = -2;
pub const SQL_C_TYPE_TIMESTAMP: SQLSMALLINT = 93;
pub const SQL_C_TYPE_DATE: SQLSMALLINT = 91;
pub const SQL_C_TYPE_TIME: SQLSMALLINT = 92;
pub const SQL_C_GUID: SQLSMALLINT = -11;
pub const SQL_C_UTINYINT: SQLSMALLINT = -28;
pub const SQL_C_STINYINT: SQLSMALLINT = -26;
pub const SQL_C_USHORT: SQLSMALLINT = -18;
pub const SQL_C_ULONG: SQLSMALLINT = -22;

// Data-at-execution constants
pub const SQL_DATA_AT_EXEC: SQLLEN = -2;
pub const SQL_LEN_DATA_AT_EXEC_OFFSET: SQLLEN = -100;

// SQL_TIMESTAMP_STRUCT
#[repr(C)]
#[derive(Default)]
pub struct SqlTimestampStruct {
    pub year: i16,
    pub month: u16,
    pub day: u16,
    pub hour: u16,
    pub minute: u16,
    pub second: u16,
    pub fraction: u32, // nanoseconds
}

#[repr(C)]
#[derive(Default)]
pub struct SqlDateStruct {
    pub year: i16,
    pub month: u16,
    pub day: u16,
}

#[repr(C)]
#[derive(Default)]
pub struct SqlTimeStruct {
    pub hour: u16,
    pub minute: u16,
    pub second: u16,
}

#[repr(C)]
pub struct SqlGuid {
    pub data1: u32,
    pub data2: u16,
    pub data3: u16,
    pub data4: [u8; 8],
}

pub const SQL_ALL_TYPES: SQLSMALLINT = 0;
